"""
Constants for aerpawlib v2 API.
"""

import os

# Connection
CONNECTION_TIMEOUT_S = 30.0
HEARTBEAT_TIMEOUT_S = 5.0
HEARTBEAT_START_DELAY_S = 1.0  # Delay before starting heartbeat monitor after first telemetry

# Movement
DEFAULT_POSITION_TOLERANCE_M = 2.0
DEFAULT_GOTO_TIMEOUT_S = 300.0
HEADING_TOLERANCE_DEG = 5.0
DEFAULT_TAKEOFF_ALTITUDE_TOLERANCE = 0.95
MIN_ARM_TO_TAKEOFF_DELAY_S = 2.0
POST_TAKEOFF_STABILIZATION_S = 1.0
ARMING_SEQUENCE_DELAY_S = 2.0
POSITION_READY_TIMEOUT_S = 60.0
ARMABLE_TIMEOUT_S = 60.0
ARMABLE_STATUS_LOG_INTERVAL_S = 5.0
POLLING_DELAY_S = 0.05
VELOCITY_UPDATE_DELAY_S = 0.05

# Validation
MIN_POSITION_TOLERANCE_M = 0.1
MAX_POSITION_TOLERANCE_M = 100.0

# State machine
STATE_MACHINE_DELAY_S = 0.01

# ZMQ
ZMQ_PROXY_IN_PORT = "5570"
ZMQ_PROXY_OUT_PORT = "5571"
ZMQ_QUERY_FIELD_TIMEOUT_S = 30.0

# Safety checker
SAFETY_CHECKER_REQUEST_TIMEOUT_S = 10.0
SERVER_STATUS_REQ = "server_status_req"
VALIDATE_WAYPOINT_REQ = "validate_waypoint_req"
VALIDATE_CHANGE_SPEED_REQ = "validate_change_speed_req"
VALIDATE_TAKEOFF_REQ = "validate_takeoff_req"
VALIDATE_LANDING_REQ = "validate_landing_req"

# AERPAW
DEFAULT_FORWARD_SERVER_IP = os.getenv("AP_EXPENV_OEOCVM_XM", "192.168.32.25")
DEFAULT_FORWARD_SERVER_PORT = 12435
